# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vxtFfXOI8yCjD1nrJMYOfV0mfIU0ktz
"""

with open('harry_potter.txt','r')as f:
  hi=f.read()

hi

splitted_data=hi.split("\n")
splitted_data

title=splitted_data[0]
title

author=splitted_data[-1]
author

titleyear=splitted_data[1:-1]
titleyear

D={}
i=0
for i in range(len(titleyear)):
  k=title+""+str(i+1)
  D[k]=None

D

titleList =[]
yearList =[]
for i in titleyear:
  temp=i.split("(")
  title = temp[0].strip()
  year = temp[1].strip()[:-1]
  titleList.append(title)
  yearList.append(year)
print(titleList)
print(yearList)

i=0
for key in D:
  D[key] = {"title" : titleList[i],"year":yearList[i],"author":author}
  i+=1

for key in D:
  print(key,D[key])

